[versions]
kotlin = "2.2.20"
koog = "0.4.2"

[libraries]
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
koog-tools = { module = "ai.koog:agents-tools", version.ref = "koog" }
executor = { module = "ai.koog:prompt-executor-llms", version.ref = "koog" }
openai-executor = {module = "ai.koog:prompt-executor-openai-client-base", version.ref = "koog" }


[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
